# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import evaluate_pb2 as evaluate__pb2


class PhaFicStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.evaluate = channel.unary_unary(
                '/PhaFic/evaluate',
                request_serializer=evaluate__pb2.request.SerializeToString,
                response_deserializer=evaluate__pb2.response.FromString,
                )


class PhaFicServicer(object):
    """Missing associated documentation comment in .proto file."""

    def evaluate(self, request, context):
        """runs solver for the requested point and 
        returns computed distance from the target morphology 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhaFicServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.evaluate,
                    request_deserializer=evaluate__pb2.request.FromString,
                    response_serializer=evaluate__pb2.response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PhaFic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PhaFic(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PhaFic/evaluate',
            evaluate__pb2.request.SerializeToString,
            evaluate__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
