# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evaluate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65valuate.proto\"\xbe\x02\n\x07request\x12\x33\n\x0e\x61\x63quired_point\x18\x01 \x03(\x0b\x32\x1b.request.AcquiredPointEntry\x12/\n\x0clower_bounds\x18\x02 \x03(\x0b\x32\x19.request.LowerBoundsEntry\x12/\n\x0cupper_bounds\x18\x03 \x03(\x0b\x32\x19.request.UpperBoundsEntry\x1a\x34\n\x12\x41\x63quiredPointEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1a\x32\n\x10LowerBoundsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1a\x32\n\x10UpperBoundsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"D\n\x08response\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x12\x12\n\ntime_taken\x18\x03 \x01(\x05\x32)\n\x06PhaFic\x12\x1f\n\x08\x65valuate\x12\x08.request\x1a\t.responseb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['request']
_REQUEST_ACQUIREDPOINTENTRY = _REQUEST.nested_types_by_name['AcquiredPointEntry']
_REQUEST_LOWERBOUNDSENTRY = _REQUEST.nested_types_by_name['LowerBoundsEntry']
_REQUEST_UPPERBOUNDSENTRY = _REQUEST.nested_types_by_name['UpperBoundsEntry']
_RESPONSE = DESCRIPTOR.message_types_by_name['response']
request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {

  'AcquiredPointEntry' : _reflection.GeneratedProtocolMessageType('AcquiredPointEntry', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_ACQUIREDPOINTENTRY,
    '__module__' : 'evaluate_pb2'
    # @@protoc_insertion_point(class_scope:request.AcquiredPointEntry)
    })
  ,

  'LowerBoundsEntry' : _reflection.GeneratedProtocolMessageType('LowerBoundsEntry', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_LOWERBOUNDSENTRY,
    '__module__' : 'evaluate_pb2'
    # @@protoc_insertion_point(class_scope:request.LowerBoundsEntry)
    })
  ,

  'UpperBoundsEntry' : _reflection.GeneratedProtocolMessageType('UpperBoundsEntry', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_UPPERBOUNDSENTRY,
    '__module__' : 'evaluate_pb2'
    # @@protoc_insertion_point(class_scope:request.UpperBoundsEntry)
    })
  ,
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'evaluate_pb2'
  # @@protoc_insertion_point(class_scope:request)
  })
_sym_db.RegisterMessage(request)
_sym_db.RegisterMessage(request.AcquiredPointEntry)
_sym_db.RegisterMessage(request.LowerBoundsEntry)
_sym_db.RegisterMessage(request.UpperBoundsEntry)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'evaluate_pb2'
  # @@protoc_insertion_point(class_scope:response)
  })
_sym_db.RegisterMessage(response)

_PHAFIC = DESCRIPTOR.services_by_name['PhaFic']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST_ACQUIREDPOINTENTRY._options = None
  _REQUEST_ACQUIREDPOINTENTRY._serialized_options = b'8\001'
  _REQUEST_LOWERBOUNDSENTRY._options = None
  _REQUEST_LOWERBOUNDSENTRY._serialized_options = b'8\001'
  _REQUEST_UPPERBOUNDSENTRY._options = None
  _REQUEST_UPPERBOUNDSENTRY._serialized_options = b'8\001'
  _REQUEST._serialized_start=19
  _REQUEST._serialized_end=337
  _REQUEST_ACQUIREDPOINTENTRY._serialized_start=181
  _REQUEST_ACQUIREDPOINTENTRY._serialized_end=233
  _REQUEST_LOWERBOUNDSENTRY._serialized_start=235
  _REQUEST_LOWERBOUNDSENTRY._serialized_end=285
  _REQUEST_UPPERBOUNDSENTRY._serialized_start=287
  _REQUEST_UPPERBOUNDSENTRY._serialized_end=337
  _RESPONSE._serialized_start=339
  _RESPONSE._serialized_end=407
  _PHAFIC._serialized_start=409
  _PHAFIC._serialized_end=450
# @@protoc_insertion_point(module_scope)
